const char* PROMPT_STRING =
    "The program supports the following commands:\n"
    "\"archiver -c archive_name file1 [file2 ...]\" - archives files file1, file2, ... and put the result in file archive_name.\n"
    "\"archiver -d archive_name\" - extracts files from the archive archive_name and place them in the current directory, keeping file names\n"
    "\"archiver -h\" - shows prompts on using the program.\n";